### ISSUE TITLE
Please create documentation 

### ISSUE THREAD

**Issue by tufail** [medmain/react-openseadragon#8]
Hi Guys,

Great work here!
Could you please share the documentation for all components . So that it will be easy for us to use these components. 
- What are props we can use in OpenSeadragon main component and how to use the Overlay component.

**Comment by michaelrambeau** [comment]
Hello @tufail 
Sorry for the late reply.
Unfortunately this project is not maintained anymore and we don't provide any support.

However if you wanted to use some of the code for your needs, I can provide 2 hints, to reply to your question:

The main component props are specified in the `PropTypes`, check here: https://github.com/medmain/react-openseadragon/blob/acc6db3ec86af3ef25f55d28ca8c41d2223f9835/package/src/main.js#L16-L32

`<Overlay>` is a component used to add layers on top of Openseadragon viewer, it has to be a direct child of `<OpenSeadragon>` main component.

```jsx
<OpenSeadragon>
  <Overlay>Layer 1</Overlay>
  <Overlay>Layer 2</Overlay>
</OpenSeadragon>
```
